---

- name: Enable the traffic forwarding
  sysctl:
    name: net.ipv4.ip_forward
    sysctl_set: yes
    value: 1
    state: present
    reload: yes
  become: yes

- name: Set up NAT using firewalld
  include_tasks: firewalld.yml
  when: nat_router_mode == 'firewalld'

- name: Set up NAT using UFW
  include_tasks: ufw.yml
  when: nat_router_mode == 'ufw'
